on: [workflow_dispatch, push]

jobs:
  universal_580:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          /usr/bin/python3 -m pip install pyinstaller==5.8.0
          /Users/runner/Library/Python/3.8/bin/pyinstaller --version
          /Users/runner/Library/Python/3.8/bin/pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main

  _590:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          /usr/bin/python3 -m pip install pyinstaller==5.9.0
          /Users/runner/Library/Python/3.8/bin/pyinstaller --version
          /Users/runner/Library/Python/3.8/bin/pyinstaller --onedir --noupx --debug all main.py
          ./dist/main/main

  univeral_590:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          /usr/bin/python3 -m pip install pyinstaller==5.9.0
          /Users/runner/Library/Python/3.8/bin/pyinstaller --version
          /Users/runner/Library/Python/3.8/bin/pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main

  universal_dev:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          /usr/bin/python3 -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
          /Users/runner/Library/Python/3.8/bin/pyinstaller --version
          /Users/runner/Library/Python/3.8/bin/pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main
