on: [workflow_dispatch, push]

jobs:
  universal_580:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          pip3 install pyinstaller==5.8.0
          pyinstaller --version
          pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main

  _590:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          pip3 install pyinstaller==5.9.0
          pyinstaller --version
          pyinstaller --onedir --noupx --debug all main.py
          ./dist/main/main

  univeral_590:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          pip3 install pyinstaller==5.9.0
          pyinstaller --version
          pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main

  universal_dev:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: |
          /usr/bin/python3 --version --version
          pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
          pyinstaller --version
          pyinstaller --onedir --noupx --debug all --target-architecture universal2 main.py
          ./dist/main/main
